sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  apt: true
  pip: false
install:
  - pip install unittest2 mock==1.0.1 flake8
  - python setup.py clean --all
  - python setup.py install
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 smooch; fi
  - python -W always setup.py test
matrix:
  allow_failures:
    - python: pypy
